### ISSUE TITLE
How to set property of a dynamically created component?

### ISSUE THREAD

**Issue by Ahthe45th** [ysfchn/DynamicComponents-AI2#11]
I have a dynamically created component that i want to set the value of as in this picture

![Screenshot at 2020-06-08 04-24-16](https://user-images.githubusercontent.com/21014011/84008609-9e3de600-a961-11ea-8b69-2f561ae07e5d.png)

how do i access said dynamic component and change its value?

**Comment by ysfchn** [comment]
You can use Any Component blocks for that.

![image](https://user-images.githubusercontent.com/54748183/84021273-f63e1200-a98c-11ea-9b50-182bd3985a07.png)

Alternatively, you can use SetProperty block too but it might not work with all values.
