### ISSUE TITLE
How to create dynamic component within other a verticalscroll layout

### ISSUE THREAD

**Issue by Ahthe45th** [ysfchn/DynamicComponents-AI2#12]
I want to create a dynamic component in another one as in this picture. Im assuming the in is where you would want it to be put but it's not working. Also how do I specify which component i want it to be?

![Screenshot at 2020-06-08 04-24-16](https://user-images.githubusercontent.com/21014011/84008609-9e3de600-a961-11ea-8b69-2f561ae07e5d.png)

How do I do so?

**Comment by ysfchn** [comment]
To get the component's itself from an ID, use the **GetComponent** block.

![image](https://user-images.githubusercontent.com/54748183/84022007-42d61d00-a98e-11ea-8d31-f7b818196875.png)

Also, try typing "TextBox" instead of "textbox".

**Comment by alanscot** [comment]
After I click on button "CreateComponentButton" the TextBox successfully appears ( and another textbox contains all of the DesignProperty names for a TextBox)
BUT
When I click on SetPropertiesButton  -- I get error 
java.lang.NoSuchMethodError: 
No virtual method getParameterCount()I in class Ljava/lang/reflect/Method;
 or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)
In App Inventor v2 April 14 Build
![DynamicComponents_Java_Error](https://user-images.githubusercontent.com/7455851/84052436-6c2e8300-a965-11ea-8739-134507b3e3c0.JPG)

**Comment by ysfchn** [comment]
See my reply on #13
