### ISSUE TITLE
Java Error in SetProperty

### ISSUE THREAD

**Issue by alanscot** [ysfchn/DynamicComponents-AI2#13]
After I click on button "CreateComponentButton" the TextBox successfully appears ( and another textbox contains all of the DesignProperty names for a TextBox)
BUT
When I click on SetPropertiesButton -- I get error
java.lang.NoSuchMethodError:
No virtual method getParameterCount()I in class Ljava/lang/reflect/Method;
or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)
In App Inventor v2 April 14 Build
![DynamicComponents_Java_Error](https://user-images.githubusercontent.com/7455851/84055315-85393300-a969-11ea-8410-1e92085c6b6c.JPG)

**Comment by alanscot** [comment]
the .aia would be attached  -- but as usual Github craps again by only allowing txt or zip or pdf

**Comment by alanscot** [comment]
But what we REALLY need is Height and Width but that doesn't show up in the list GetDesignerProperties :(

**Comment by ysfchn** [comment]
I already fixed this issue with 3d037f6c371afd21cced5df594a669682b1f6037 . You can wait for the new release, build with the sources, or use **Any Component** blocks to set properties instead of the **SetProperty**.

**Comment by alanscot** [comment]
Thankyou SO MUCH !

I never thor about using the ANY COMPONENT.

Where can I send you money via Paypal ?

Alan
     On Monday, June 8, 2020, 10:32:28 AM PDT, Yusuf Cihan <notifications@github.com> wrote:  
 
 


I already fixed this issue with 3d037f6 . You can wait for the new release, build with the sources, or use Any Component blocks to set properties instead of the SetProperty.

**Comment by ysfchn** [comment]
@alanscot Thank you! Sadly, PayPal is not available in my country so I can't get money from there, however I'm working on creating a Patreon page, thank you for your interest!

**Comment by Ahthe45th** [comment]
Where does one get the new release? Or any of the releases for that matter?

**Comment by ysfchn** [comment]
Releases of the extension can be found on [Releases](https://github.com/ysfchn/DynamicComponents-AI2/releases). The latest version contains more features.

**Comment by ysfchn** [comment]
As I said, it is fixed with a commit but not released yet. You can build from the sources or use Any Component blocks.

**Comment by ysfchn** [comment]
I will close the issue as problem has been fixed with 3d037f6c371afd21cced5df594a669682b1f6037
