### ISSUE TITLE
Support for extensions in Schema

### ISSUE THREAD

**Issue by WaterMelonOof** [ysfchn/DynamicComponents-AI2#16]
If we simply use block to create a component from another extension, it works perfectly. However, using schema to type the whole internal name of that extension component won't work. It throws an error, saying that it is attempting to create com.google.appinventor.com...(the internal name of extension)

**Comment by ysfchn** [comment]
Schemas only allow internal components, for now. But I can try adding compatibility for supporting extension components in templates.

**Comment by WaterMelonOof** [comment]
Thanks!

**Comment by ysfchn** [comment]
I added support for typing full class names of extension with 4c05de4dcd37e54d25942218deb115d326245c79 commit.

So you will able to type the full name of extension class names in Schema or in Create block directly when I release the new version.
