### ISSUE TITLE
Releasing the extension: Asynchronous or/and Synchronous

### ISSUE THREAD

**Issue by ysfchn** [ysfchn/DynamicComponents-AI2#19]
Looks like people are not happy with the app hanging because of creating a lot of blocks. The extension works synchronously right now, but it may be a good choice to work with asynchronous too. Yes, asynchronous tasks have their own pros and cons, but synchronous tasks have too.

This issue created because some people in the Kodular community asked for making the extension asynchronous, so as I'm not sure about yet, I will wait until I get some feedback about this issue.

**Comment by patryk84a** [comment]
In my opinion, both modes would be a good solution.

**Comment by ysfchn** [comment]
But how should I release it? As two extensions?

**Comment by alanscot** [comment]
I have an AP that creates around 25 labels and 15 Arrangements  all at once and has been doing successfully for several days now ! So STATUS QUO for me !

**Comment by StormiFire** [comment]
@ysfchn Which blocks would need to be _Async_?

**Comment by ysfchn** [comment]
> @ysfchn Which blocks would need to be _Async_?

If extension would release as Async, then I think almost all blocks would need to be Async. But most important ones are, `Create`, `Schema`, `SetProperties`

**Comment by StormiFire** [comment]
> > @ysfchn Which blocks would need to be _Async_?
> 
> If extension would release as Async, then I think almost all blocks would need to be Async. But most important ones are, `Create`, `Schema`, `SetProperties`

Well the whole extension could be _Async_? What would be the cons & pros of doing this?

**Comment by ysfchn** [comment]
> Well the whole extension could be Async? What would be the cons & pros of doing this?

Here is a table that I posted on the community before [in this post](https://community.kodular.io/t/free-open-source-dynamic-components-extension-for-every-component/50789/1059?u=yusufcihan).

|| Asynchronous | Synchronous (current) |
|----------|:---------------------:|:--------------------:|
|Execution Speed|✅ Same |✅ Same|
|Execution Time|✅ Same |✅ Same|
|Execution Method|✅ Doesn't hang the main thread, <br>other blocks will be executed **before** previous has task completed.|❌ Hangs the main thread, <br>other blocks will be executed **after** previous task has completed.|
|What happens when executing `Create` block|❌ It is **unknown** if the component is created or not because Create block **won't wait** until the component is created.|✅ It is **known** that component is created because Create block **will wait** until the component is created.|
|What happens when executing `SetProperty` block|❌ It **may** give an error if the component is still not created yet.|✅ It **never** gives an error because Create block will hang app until the component has created.|
|How to learn if the component is created **without an event**?|❌ Use a Clock to check if the component is created continuously. **Otherwise, you can't know without using an event.**|✅ When the next block executes.|
|How to learn if the component is created **with an event**?|✅ Use the related event. |✅ When the next block executes, or use the related event.|

**Comment by alanscot** [comment]
As I replied before -- I have no problem creating around 20+ Arrangements and 20+ Labels all at the same time so I'm definitely FOR   Synchronous if this is the consequence of Asynchronous !
    On Tuesday, August 25, 2020, 07:58:36 AM PDT, Yusuf Cihan <notifications@github.com> wrote:  
 
 



Well the whole extension could be Async? What would be the cons & pros of doing this?


Here is a table that I posted on the community before in this post.

|  | Asynchronous | Synchronous (current) |
| Execution Speed |  ✅ Same |  ✅ Same |
| Execution Time |  ✅ Same |  ✅ Same |
| Execution Method |  ✅ Doesn't hang the main thread, 
other blocks will be executed before previous has task completed. |  ❌ Hangs the main thread, 
other blocks will be executed after previous task has completed. |
| What happens when executing Create block |  ❌ It is unknown if the component is created or not because Create block won't wait until the component is created. |  ✅ It is known that component is created because Create block will wait until the component is created. |
| What happens when executing SetProperty block |  ❌ It may give an error if the component is still not created yet. |  ✅ It never gives an error because Create block will hang app until the component has created. |
| How to learn if the component is created without an event? |  ❌ Use a Clock to check if the component is created continuously. Otherwise, you can't know without using an event. |  ✅ When the next block executes. |
| How to learn if the component is created with an event? |  ✅ Use the related event. |  ✅ When the next block executes, or use the related event. |

**Comment by ysfchn** [comment]
Yes, most people not having a problem with it but some people creating more than 100 components, so looks like an extension causing the app to hang. However, my vote would be staying at synchronous too.

**Comment by StormiFire** [comment]
> > Well the whole extension could be Async? What would be the cons & pros of doing this?
> 
> Here is a table that I posted on the community before [in this post](https://community.kodular.io/t/free-open-source-dynamic-components-extension-for-every-component/50789/1059?u=yusufcihan).
> 
> Asynchronous	Synchronous (current)
> Execution Speed	✅ Same	✅ Same
> Execution Time	✅ Same	✅ Same
> Execution Method	✅ Doesn't hang the main thread,
> other blocks will be executed **before** previous task has completed.	❌ Hangs the main thread,
> other blocks will be executed **after** previous task has completed.
> What happens when executing `Create` block	❌ It is **unknown** if the component is created or not because Create block **won't wait** until the component is created.	✅ It is **known** that component is created because Create block **will wait** until the component is created.
> What happens when executing `SetProperty` block	❌ It **may** give an error if the component is still not created yet.	✅ It **never** gives an error because Create block will hang app until the component has created.
> How to learn if the component is created **without an event**?	❌ Use a Clock to check if the component is created continuously. **Otherwise, you can't know without using an event.**	✅ When the next block executes.
> How to learn if the component is created **with an event**?	✅ Use the related event.	✅ When the next block executes, or use the related event.

Last moment thought about the `SetProperty` block, but what if we queue properties to be set on a component? For example...

For each `SetProperty` block that contains the `Id` of a component, we can add the name and value to a `JSONObject` that's associated with the component `Id`. When the component is created, we can check if that `Id` is in the set, then check for the properties and create a `YailDictionary` from them. Afterwards, just execute `SetProperties` to set the properties after the component is created.

**Comment by Sonumohammad** [comment]
Add another block
Create Asynchronously
And add event OnCreate

**Comment by StormiFire** [comment]
> Add another block
> Create Asynchronously
> And add event OnCreate

`OnCreate()` was discussed between @ysfchn and I privately. There is a plan to add it.

**Comment by StormiFire** [comment]
@ysfchn I'm wondering, what if we store the methods in a `HashMap` so that when a component is created, the next one will run? Maybe we can create a structure using JSON and store it, then pass those properties to the appropriate blocks, if you know what I mean.

**Comment by StormiFire** [comment]
@ysfchn I am working on testing asynchronous operations.

**Comment by StormiFire** [comment]
@ysfchn Take a look at #35 for me.
