### ISSUE TITLE
Template tool ignores the value types

### ISSUE THREAD

**Issue by patryk84a** [ysfchn/DynamicComponents-AI2#21]
System: Windows 10 64bit
Python: 3.8.5

I get the message: 
Traceback (most recent call last):
  File "C:\Users\Karolina\Desktop\szablony\TemplateCreate.py", line 5, in <module>
    from flatten_json import flatten, unflatten_list
ModuleNotFoundError: No module named 'flatten_json'

Flatten_json installed. When I try to install, I get:
Requirement already satisfied: flatten_json in c:\users\karolina\.platformio\penv\lib\site-packages (from -r requirements.txt (line 1)) (0.1.7)

**Comment by ysfchn** [comment]
I updated the `requirements.txt`, can you try installing the module from there again?
`pip install -r requirements.txt`

**Comment by patryk84a** [comment]
Same situation as above. But I was able to start by copying all the necessary scripts to the directory where the cli.py script is located.

**Comment by patryk84a** [comment]
I was able to create a json file. After adding it to the app in inventor, I get the message:
"method com.google.appinventor.components.runtime.Label.FontBold argument 1 has type boolean, got java.lang.String"

**Comment by ysfchn** [comment]
Can you attach your AIA and the generated JSON?

**Comment by patryk84a** [comment]
This is the aia from which I was generating json:
[aia1](https://drive.google.com/file/d/1bgnrbmQ4DfTgZUkygKpQhG58MnKpLOkV/view?usp=sharing)

This is the generated json:
[json](https://drive.google.com/file/d/1XLBkQ7jQKRaONgmLccIWxWO9e1H0exsf/view?usp=sharing)

This is aia with dynamic component creation: 
[aia2](https://drive.google.com/file/d/1b4d1RmWhC53PRIvOeWcN10c_sp89qxMj/view?usp=sharing)

Besides the problem with properties where the value is a boolean variable, there is also a problem with color values in the form: & HFFFFFFFF. After removing all properties from true, false and colors the application works.

**Comment by patryk84a** [comment]
Ok, I deleted "" where not needed and changed colors from hex to dec. The application works but does not take colors into account. For example, instead of & HFFFFFFFF I entered 16777215, I don't know if this is the correct value for appinventor. I also tried the red color 255. Unfortunately, everything is still white.

**Comment by patryk84a** [comment]
For the appinventor platform, could you add such a color formula to the script?

N = B + (G + (R + (256 x opacity)) x 256) x 256
Eg.
N = 0 + (255 + (255 + (256 x 255)) x 256) x 256 = 4294967040

**Comment by ysfchn** [comment]
That's because App Inventor saves the all types of values in string in AIA files. So it is normal for TemplateCreator to do the same.

![image](https://user-images.githubusercontent.com/54748183/90333055-21676200-dfcb-11ea-831a-c44b1c870446.png)

Maybe I can add an exception for colors, thanks for reporting it.

**Comment by patryk84a** [comment]
It would also be impossible to make such exceptions for numeric values to remove "".?

**Comment by ysfchn** [comment]
Yes, but it will take some time as I will write the all properties and their required types manually.

**Comment by ysfchn** [comment]
Hi,

I fixed the issue with 274d84ea214c22759b1354f767c45f6711a9ec63 commit, and it works as expected with your provided sample AIA files. if you want to try yourself too, just fetch the repository again.

**Comment by ysfchn** [comment]
I will close the issue as it is fixed, if you still encounter issues, you are free to open new one.
