### ISSUE TITLE
AppInventor problem with numeric value in "text"

### ISSUE THREAD

**Issue by patryk84a** [ysfchn/DynamicComponents-AI2#32]
Today I discovered a problem. In the text field I have an initial value of 0. Schema generator sets the value: "Text": 0. For AppInventor this is an error because it should be "Text": "0". He correctly puts text values in quotation marks.

**Comment by StormiFire** [comment]
@ysfchn Is this dealing with the `Schema` block or `TemplateCreator`?

**Comment by StormiFire** [comment]
@ysfchn @patryk84a I have found a fix for the issue and will include it in #35

**Comment by patryk84a** [comment]
I forgot to add. This problem was with "TemplateCreate".

**Comment by ysfchn** [comment]
Closing as this has fixed with #35
