### ISSUE TITLE
Impossible to set speed parameter

### ISSUE THREAD

**Issue by landscht** [ysfchn/DynamicComponents-AI2#33]
Hello!

I code the game "piano tiles" that you must surely know. For this I need to generate sprite images until the game is finished. I manage to generate the sprite images, to set x, y, height, width but I can't set speed, so my sprite images don't move. I tried with a schema and the creation block by name.

**Comment by ysfchn** [comment]
Yes, it is a known issue. But the fact is I don't do any modifications to Sprites, so it is about how App Inventor behaves to Sprites. Because other components are working correctly.

**Comment by landscht** [comment]
Okay, don't you have an alternative to counter this problem?

**Comment by ysfchn** [comment]
Not yet, unfortunately.

**Comment by StormiFire** [comment]
@landscht Can you show your blocks from the generation of the Sprite, to properties being set for them?

**Comment by StormiFire** [comment]
@ysfchn @landscht I have found a fix for the issue and will include it in #35

**Comment by ysfchn** [comment]
Closing as this has fixed with #35
