### ISSUE TITLE
Creating from existing component block doesn't work anymore

### ISSUE THREAD

**Issue by ysfchn** [ysfchn/DynamicComponents-AI2#38]
![image](https://user-images.githubusercontent.com/54748183/104018076-481c7400-51ca-11eb-8c03-72631e11ebac.png)

_[Related post](https://community.kodular.io/t/which-is-this-error/100071/19?u=yusufcihan)_

![image](https://user-images.githubusercontent.com/54748183/104017736-b6146b80-51c9-11eb-8f96-332069afac6e.png)

_[Image source](https://community.kodular.io/t/dynamic-component-error-in-companion/100805?u=yusufcihan)_

### Possible Cause:

https://github.com/ysfchn/DynamicComponents-AI2/blob/facb5dfa42c63e778dcac399cfa85d2aefc1a9c7/src/com/yusufcihan/DynamicComponents/DynamicComponents.java#L189-L195

Because of that, it appends the `BASE` value again even if the component name already includes the `com.google.appinventor.components.runtime` package name. It must delete this piece from the component name too if it already exists.

### Possible Fix:

Add another replace method to remove `com.google.appinventor.components.runtime.` from component name.

**Comment by StormiFire** [comment]
I will take care of this today. Thanks for reporting it.

**Comment by ysfchn** [comment]
Fixed with #39
