### ISSUE TITLE
Load from a Schema JSON

### ISSUE THREAD

**Issue by ysfchn** [ysfchn/DynamicComponents-AI2#4]
It can be easier to create dynamic components by using a single block instead of using a lot of blocks for each component. So the extension should be able to create components by passing a JSON which is can be read by extension.

Like this:
```json
{
    "components": [
        {
            "type": "Button",
            "id": "1",
            "properties": [
                {
                    "Enabled": true,
                    "Text": "Text for Button1"
                }
            ]
        }
    ]
}
```

**Comment by ShreyashSaitwal** [comment]
I'd like to work on this.
