### ISSUE TITLE
example needed

### ISSUE THREAD

**Issue by better319** [ysfchn/DynamicComponents-AI2#40]
are there any example ?
url pls!!
Thanks!!!!

**Comment by ysfchn** [comment]
You can check Kodular Community to see example apps that made with this extension.

You can also look at the "Showcase" in the extension topic.
https://community.kodular.io/t/f-os-dynamic-components-extension-for-every-component-2-2-1/50789

**Comment by better319** [comment]
THANK YOU VERY MUCH!!!

**Comment by ysfchn** [comment]
You're welcome, feel free to create another issue if you need something else.

**Comment by alanscot** [comment]
With over 1,500 comments this pagehttps://community.kodular.io/t/f-os-dynamic-components-extension-for-every-component-2-2-1/50789 is UNUSABLE ! (Especially when it is the most recent comments do not come first)Where's the FAQ and MOST RELEVANT info? 
    On Tuesday, January 12, 2021, 12:27:23 AM PST, Yusuf Cihan <notifications@github.com> wrote:  
 
 


You can check Kodular Community to see example apps that made with this extension.

You can also look at the "Showcase" in the extension topic.
https://community.kodular.io/t/f-os-dynamic-components-extension-for-every-component-2-2-1/50789

**Comment by ysfchn** [comment]
> Where's the FAQ and MOST RELEVANT info? 
You can find every important information in the first post, like in others.

**Comment by better319** [comment]
there were something wrongwith my account? if it's possible cloud you put an example on the github?
THANKS VERY MUCH!!

**Comment by better319** [comment]
in addition,maybe there are something wrong with v179-31-g316f93e0-dirty   2.55or2.55u，offline version
 
![360截图20210409204629784](https://user-images.githubusercontent.com/13842581/114183954-d396d400-9976-11eb-95bb-86848875593e.jpg)
![360截图20210409204608255](https://user-images.githubusercontent.com/13842581/114183960-d5609780-9976-11eb-8cbe-c2c482bcc268.jpg)

**Comment by ysfchn** [comment]
> if it's possible would you put an example on the github? just create an button

There is [already a topic on Kodular Community](https://community.kodular.io/t/f-os-dynamic-components-extension-for-every-component-2-2-2/50789) about the extension, and you can scroll down to "Showcase" section to see example projects.

> in addition,maybe there are something wrong with v179-31-g316f93e0-dirty 2.55or2.55u，offline version

Blocks are displayed by AI2 distribution that you use, the extension just defines the blocks.
