### ISSUE TITLE
an error had happend in my offline version 

### ISSUE THREAD

**Issue by better319** [ysfchn/DynamicComponents-AI2#44]
![11](https://user-images.githubusercontent.com/13842581/114295732-b62e4b00-9ad9-11eb-914e-4d85d55c18a0.jpg)

![22](https://user-images.githubusercontent.com/13842581/114295734-baf2ff00-9ad9-11eb-80ee-cd1b3386f8e9.jpg)

![33](https://user-images.githubusercontent.com/13842581/114295735-bdedef80-9ad9-11eb-93c4-676eb8842da5.jpg)

**Comment by better319** [comment]
![360截图20210411152519492](https://user-images.githubusercontent.com/13842581/114295812-24730d80-9ada-11eb-9ab7-c69b371b771f.jpg)

**Comment by ysfchn** [comment]
Can you reconnect again or try with another extension? Also, looks it is not related to the extension because it works correctly in online distributions.

**Comment by better319** [comment]
https://sourceforge.net/projects/ai2offline/files/2.8/
 

it's the url where  i download from,if it's possible ,pls try it .
THANKS!

**Comment by better319** [comment]
AI2Offline_x64.exe   VERSION

**Comment by better319** [comment]
in some ai2 web site it's also had problem(wxbit),and some not（mit ）

i test the  different between mit ai2  and the offline version.
here are  the differences ,below:


![微信截图_20210414094709](https://user-images.githubusercontent.com/13842581/114642785-15bd6e00-9d07-11eb-97d3-6410baae167b.png)

**Comment by ysfchn** [comment]
As I said, it is not related to the extension, please contact your AI2 distribution developer.
