### ISSUE TITLE
Crash on creating a Component

### ISSUE THREAD

**Issue by Florian-Mahlberg** [ysfchn/DynamicComponents-AI2#52]
Hey, I wanted to create an ImageSprite with DynamicComponents, but my App crashes since using this extension. Here is my code:

<img width="979" alt="blocks" src="https://user-images.githubusercontent.com/53428387/145254305-181bc7d3-8a72-4403-8f85-e30467722b91.png">

Thanks for your help, it's a school project, so I may need an answer soon. Ill upload this code on community.appinventor.mit.edu as well, and if this problem is fixed by the community, Ill close this issue and post a link.

**Comment by ysfchn** [comment]
Can you provide a AIA (with assets you are setting to component - if they are not private) that reproduces this issue?

**Comment by Florian-Mahlberg** [comment]
My Image is just a 4k black Image: 
![Image](https://user-images.githubusercontent.com/53428387/145408821-b31e5e7e-ec58-404c-952e-9e90acc5687c.PNG)
And my code is here: 
https://florianscool.glitch.me/code

**Comment by ysfchn** [comment]
Actually if "wall1" was a ImageSprite component, it should have worked without any issues. But I'm happy to see that you found a workaround. I will close the issue now (I will create a new one myself if I can reproduce the issue), you can create a new issue if you encounter another issue!

**Comment by Florian-Mahlberg** [comment]
Okay, great. I uploaded a version with bugs here: [Download](https://florianscool.glitch.me/code), if you want to check it out. Sorry it's a bit messy 😅
