### ISSUE TITLE
How to add if statement in JSON

### ISSUE THREAD

**Issue by InvenceSaltillo** [ysfchn/DynamicComponents-AI2#53]
How to add if statement in JSON I trying this but doesnt work

`{
                    "id": "Label{id}",
                    "type": "Label",
                    "properties": {
                        "FontBold": true,
                        "FontTypefaceImport": "PTSansNarrow-Regular.ttf",
                        "if": { "{stock}": 1 },

                        "then": {
                            "Text": "{productName}"
                        },
                        "else": { "Text": "NO HAY" },
                        "TextColor": 4294967295
                    }
                }`

**Comment by ysfchn** [comment]
Conditional statements like "if"s are not supported in schema, you need to do these checks in blocks instead.
