### ISSUE TITLE
Error de Ui

### ISSUE THREAD

**Issue by Macroseso** [ysfchn/DynamicComponents-AI2#55]
Greetings, when the extension creates the components it blocks the application for a few moments until it shows them

**Comment by ysfchn** [comment]
![resim](https://user-images.githubusercontent.com/54748183/198308457-fd13a1ac-407e-401b-9669-311281c534b4.png)

**Comment by Macroseso** [comment]
i selected UI but it still blocking my app for a few seconds

**Comment by Macroseso** [comment]
i ll show you my code on kodular comunity

**Comment by ysfchn** [comment]
There may be other extensions/components that blocks the application. Also, seeing that you asked in multiple places, community DM, a new topic, as a post on Dynamic Components' topic and here on GitHub, [I prefer to continue the discussion in one place.](https://community.kodular.io/t/dynamic-component-ui-error/201151?u=yusufcihan)

**Comment by Macroseso** [comment]
[ysfchn](https://github.com/ysfchn) Good afternoon i continued the discussion [here](https://community.kodular.io/t/dynamic-component-ui-error/201151?u=yusufcihan)
