### ISSUE TITLE
Error Creating Object

### ISSUE THREAD

**Issue by Corotyest** [ysfchn/DynamicComponents-AI2#59]
Good afternoon. Recently I started using this extension, and I encountered and error, an apology in advance if I'm wrong doing something, however I think I'm not.

An Illustrative image of the error thrown by the application.
![Screenshot_2023-03-30-13-09-31-25_8bc570bc48cefd32d9827ae61d5ef2ab.jpg](https://user-images.githubusercontent.com/74837790/228940029-9f71c104-7434-47a7-ba5b-55413d652f94.jpg)

**Comment by Corotyest** [comment]
Though that I was reading it badly. As the first argument `in`, I'm passing the `Screen` Instance, if it need to be.

**Comment by alanscot** [comment]
Where's the .aia ? Attach the .aia

**Comment by Corotyest** [comment]
Hello, GitHub doesn't allow me to attach the file, but I have the latest version ( 2.2.2 ).

**Comment by ysfchn** [comment]
Hi, the extension currently doesn't accept Screen as a valid container. It needs to be an arrangement or canvas. I see that is not mentioned anywhere, so sorry for causing the confusion. I'm planning to add support for Screen in the next (probably the final) update.

**Comment by Corotyest** [comment]
Thanks fo the fast response, I understand; now it works. Super fine you support it, I think that the Invetor is unsupported.
