### ISSUE TITLE
ImageSprite cannot work

### ISSUE THREAD

**Issue by sukanemoero** [ysfchn/DynamicComponents-AI2#65]
I create some ImageSprites by your plugin
but they cant be animation after setting speed ,interval and enabled
whats happend?
<img width="797" alt="blocks" src="https://github.com/ysfchn/DynamicComponents-AI2/assets/93065841/205afa0c-b413-4a57-a801-aff2db68c9a6">

**Comment by ysfchn** [comment]
Hi! Thanks for creating an issue.

This is a known issue, and I'm hoping to fix that in the next release. As a workaround, refer here and let me know if it works for you: https://community.kodular.io/t/f-os-dynamic-components-extension-for-every-component-2-2-2/50789/2074?u=yusufcihan
