### ISSUE TITLE
Allow re-using the same schema (auto-increment ID)

### ISSUE THREAD

**Issue by ysfchn** [ysfchn/DynamicComponents-AI2#68]
The component IDs in the schema are a constant value, which means when every time someone uses the "Schema" block with the same schema JSON, they will get a "Duplicate ID" error because there would be two components having the "HorizontalArrangement1" name, which is not allowed.

```json
"id": "HorizontalArrangement1"
```

The schema format supports "template keys", which allows people to replace the placeholders with any value given from the blocks, so this can be solved easily with:

```json
{
    "keys": ["myCounter"],
    "components": [
        { "id": "HorizontalArrangement{myCounter}" }
    ]
}
```

However, this approach will depend on having a variable in the project, which needs to be incremented in each usage of the "Schema" block.

<img width="600" alt="blocks(2)" src="https://github.com/ysfchn/DynamicComponents-AI2/assets/54748183/91b05a14-226d-4a25-80c7-371342c8a138">

---

So my proposal is getting the rid of that boilerplate, and auto-incrementing the ID in the extension-part, so when someone references the "counter key" in the template:

```json
"id": "HorizontalArrangement{__counter__}"
```

The extension would replace `__counter__` with the number of how many times that Schema block is executed.

The template generator can also append `__counter__` key to each component name automatically, so this wouldn't require manual editing the template.

However, how what we should do if someone wants to use `__counter__` as a normal template key (to disable that behavior)? Maybe having a boolean property? Or maybe raise an error if `__counter__` is used as a template key? Or:

```python
{
    "keys": ["__counter__"], 
    # If "__counter__" is defined in "keys", then the user would need to replace the counter with blocks manually.
    # If not defined, replace the placeholder with an auto-incrementing number.
    "components": [
        { "id": "HorizontalArrangement{__counter__}" }
    ]
}
```

**Comment by hammerhai** [comment]
what if after the first run of a schema, right before the inflation of any component, we determine if the identifier was used previously. we do this now, but auto–incrementing would save people a lot of time. this could be opt–out behavior for anyone who would like to take their own approach. most of the following illustration is your idea.

| Schema ran `N` time | Identifier  |
| ------------- |:-------------:|
| 0      | _horizontal_arrangement_ |
| 1      | _horizontal_arrangement_1_      |
| 2      | _horizontal_arrangement_2_      |
| +      | _horizontal_arrangement_N_      |

there is a slight issue with this approach, and that is there could be multiple of the same component being inflated within one schema. at this point, although using a global variable could help, the assigning of an identifier and inflation of a component are not linearly attached. thus, a component might be assigned an identifier it wasn't supposed to be.

this could pose an issue when i test a future approach to making the inflation of a component more thread–friendly.

---

with the following approach, a global variable ("schema ran `N` time") is incremented before any component is inflated. at this point, a local variable ("`N` inflates within schema") is incremented before each inflation and the schema is being processed.

using the `name` of a schema, we can collectively count how many times it was reused.


| `N` inflates within schema | Schema ran `N` time (`<typeof name, int>`) | Identifier  |
| ------------- |:------------ |:-------------:|
| 0      | 0      | _horizontal_arrangement_0_1_ |
| 1      | 0      | _horizontal_arrangement_0_2_      |
| 2      | 0      | _horizontal_arrangement_0_3_      |
| 0      | 1      | _horizontal_arrangement_1_1_      |
| 1      | 1      | _horizontal_arrangement_1_2_      |
| +      | +      | _horizontal_arrangement_N_N_      |

```json
{
  "components": [
    {
      "id": "horizontal_arrangement"
    }
  ],
  "disable_auto_increment": false,
  "name": "something different"
}
```

---

the alternate scenario is where a user would disable auto–increment. neither the global nor local variable are affected by this change, they will just remain unused.


| `N` inflates within schema | Schema ran `N` time (`<typeof name, int>`) | Identifier  |
| ------------- |:------------ |:-------------:|
| 0      | 0      | _`horizontal_arrangement_{_identifier_}`_ |
| 1      | 1      | _`horizontal_arrangement_{_identifier_}`_      |
| 2      | 2      | _`horizontal_arrangement_{_identifier_}`_      |
| +      | +      | _`horizontal_arrangement_{_identifier_}`_      |

```json
{
  "components": [
    {
      "id": "horizontal_arrangement_{_identifier_}"
    }
  ],
  "disable_auto_increment": true,
  "keys": ["_identifier_"],
  "name": "something different with a keys field"
}
```

**Comment by ysfchn** [comment]
> there is a slight issue with this approach, and that is there could be multiple of the same component being inflated within one schema. at this point, although using a global variable could help, the assigning of an identifier and inflation of a component are not linearly attached. thus, a component might be assigned an identifier it wasn't supposed to be.

The [preferred](https://github.com/ysfchn/DynamicComponents-AI2/wiki/Creating-Templates) & easiest method of creating schemas is to generate from an existing project. So, when schemas are generated, they will already have incremental IDs by default, like `HorizontalArrangement1`, `HorizontalArrangement2` and so on.

> with the following approach, a global variable ("schema ran N time") is incremented before any component is inflated. at this point, a local variable ("N inflates within schema") is incremented before each inflation and the schema is being processed.

So I believe that approach will make things more complex, only having a global variable ("schema ran N time") should be more than enough for the most cases.

**Comment by ysfchn** [comment]
I've decided not to include this in the extension as it might go out of the scope, so it would be more appropriate to use the [schema generator](https://ysfchn.com/tools/dcai2-schema/) for these purposes.
